### ISSUE TITLE
Incorrect number of return variables from extract_basis()

### ISSUE THREAD

**Issue by tomasthurin** [Gurobi/gurobi-modelanalyzer#5]
It should be a tuple of five None not four in extract_basis if you get an exception:
https://github.com/Gurobi/gurobi-modelanalyzer/blob/master/src/gurobi_modelanalyzer/results_analyzer.py#L578

return None, None, None, None
should be changed to
return None, None, None, None, None

**Comment by mattmilten** [comment]
Good catch! I'll fix that momentarily.
